# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text=b"<a href='password/'>\xe4\xbf\xae\xe6\x94\xb9\xe5\xaf\x86\xe7\xa0\x81</a>", max_length=128, verbose_name='password'),
        ),
    ]
